name: tarcking_app
description: "Tracking app for flower application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  injectable: ^2.5.1
  get_it: ^8.2.0
  logger: ^2.6.1
  json_annotation: ^4.9.0
  dio: ^5.7.0
  retrofit: ^4.1.0
  flutter_bloc: ^9.1.1
  dartz: ^0.10.1
  flutter_secure_storage: ^9.2.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  flutter_otp_text_field: ^1.1.0
  flutter_localizations:
    sdk: flutter
  intl: any
  fluttertoast: ^8.2.14
  another_flushbar: ^1.12.32
  get: ^4.7.2
  google_fonts: ^6.2.1
  loading_indicator: ^3.1.1
  smooth_page_indicator: ^1.2.1
  country_flags: ^4.0.1
  file_picker: ^8.1.2
  flutter_svg: ^2.2.0
  shared_preferences: ^2.5.3
  mockito: ^5.4.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.0
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  bloc_test: ^10.0.0


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/font/Inter_18pt-Regular.ttf
        - asset: assets/font/Inter_18pt-Medium.ttf
        - asset: assets/font/Inter_18pt-Bold.ttf