name: Flutter Unit Tests

on:
  push:
    branches:
      - main
      - dev
      - feature/**

  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get


      - name: Run unit tests
        run: flutter test --coverage
